### ISSUE TITLE
Failure to run

### ISSUE THREAD

**Issue by swizzley** [btmura/ponzi2#1]
I followed your Youtube tutorial on getting glfw setup and I even tried running from the commit back in Feb 2017 when you published your video, but both resulted in errors. Can you help?

 .\ponzi2.exe
F0810 11:27:11.467836     996 app.go:15] glGetnCompressedTexImage
goroutine 1 [running, locked to thread]:
github.com/golang/glog.stacks(0xc042087400, 0xc042192000, 0x42, 0x98)

**Comment by swizzley** [comment]
I also watched your other tutorial with your updated workflow and ctrl+shift+B 
throws this error

'${config:ponzi2.flags}' can not be resolved because setting 'ponzi2.flags' not found.

**Comment by btmura** [comment]
Hi swiz,

I added a VS Code workspace file with the setting defined to fix the error.

Use "File > Open Workspace..." to open it and then try doing Ctrl+Shift+B.

Hope this helps,
-Brian

**Comment by mirshahriar** [comment]
Getting Error in `master` branch.

`ponzi2.go:28 glGetnCompressedTexImage`

Added `ponzi2.flags` and used `Ctrl+Shift+B`
