### ISSUE TITLE
Running ponzi2 on Linux FC27

### ISSUE THREAD

**Issue by jojo05** [btmura/ponzi2#4]
Tried to run your release from last year and also build from code. Any hints appreciated!

Thank you for open sourcing your project.

Linux: 4.18.19-100.fc27.x86_64

-----------------------

./ponzi2

No protocol specified
2020/08/10 19:06:16 PlatformError: X11: Failed to open display :0
panic: NotInitialized: The GLFW library is not initialized

-----------------------

go get -u github.com/btmura/ponzi2/...

pkg-config --cflags gl gl
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gl', required by 'virtual:world', not found
Package 'gl', required by 'virtual:world', not found
pkg-config: exit status 1

google.golang.org/grpc/internal/credentials
/home/go/external/src/google.golang.org/grpc/internal/credentials/spiffe.go:36:70: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)
/home/go/external/src/google.golang.org/grpc/internal/credentials/spiffe.go:40:47: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)
/home/go/external/src/google.golang.org/grpc/internal/credentials/spiffe.go:58:35: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)

github.com/go-gl/glfw/v3.2/glfw
In file included from /home/go/external/src/github.com/go-gl/glfw/v3.2/glfw/native_linbsd.go:9:0:
./glfw/include/GLFW/glfw3native.h:112:11: fatal error: GL/glx.h: No such file or directory
  #include <GL/glx.h>
           ^~~~~~~~~~
compilation terminated.

**Comment by jojo05** [comment]
I am now able to run the old release (sorry, I tried first from root), but I get an ERROR message without further info. 

Could you provide a more up to date release? 
How can I find out the error detail? 

I would also be interested in building from source
Thanks

**Comment by btmura** [comment]
Hi jojo, I'm not familiar with Fedora Core, but I have installed VirtualBox and have downloaded the FC 27 image. I will try building from source there and let you know. Seems like you need to install development libraries for OpenGL, GLFW, and so forth.

**Comment by jojo05** [comment]
Hi Brian,

Thank you for your help. I figured out the dependencies:

yum install libX11-devel , libXcursor-devel , libXrandr-devel , libXinerama-devel , mesa-
libGL-devel , and libXi-devel

so now  it builds 

 google.golang.org/grpc/internal/credentials
/home/go/external/src/google.golang.org/grpc/internal/credentials/spiffe.go:36:70: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)
/home/go/external/src/google.golang.org/grpc/internal/credentials/spiffe.go:40:47: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)
/home/go/external/src/google.golang.org/grpc/internal/credentials/spiffe.go:58:35: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)

**Comment by jojo05** [comment]
Hi Brian,

You should specify that  a IEX API token is required and that it can be obtained by signing for free Start plan at IEX/developers

For the release version, you should specify how to specify token before running app.

I am now struggling to get the dev environment going.

Thanks

**Comment by jojo05** [comment]
Ok, I got it to work using the Linux exe included in the code from 10 months ago, which check for the token, while v1.1 didn't.

Thanks, I will now try to build the dev enviroment so I can get the latest functionality

**Comment by jojo05** [comment]
go get fails here. Any ideas ?

google.golang.org/grpc/internal/credentials
/home/go/external/src/google.golang.org/grpc/internal/credentials/spiffe.go:36:70: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)
/home/go/external/src/google.golang.org/grpc/internal/credentials/spiffe.go:40:47: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)
/home/go/external/src/google.golang.org/grpc/internal/credentials/spiffe.go:58:35: state.PeerCertificates[0].URIs undefined (type *x509.Certificate has no field or method URIs)

**Comment by btmura** [comment]
Hi jojo,

Glad to hear you got the dependencies figured out. I should add those to the README file! In addition to the ones you listed, I also had to install gcc.

You are absolutely right about how the IEX API token should be documented. It became a requirement when IEX launched their new IEX Cloud API. I was thinking of asking for the token when the program starts up, but I haven't gotten around to that.

As for the spiffe.go error, I wonder if you need to update your go version, since I don't get this error when I use the most recent version of Go 1.15.  I guess this gRPC dependency is for ponzi2server which was an experiment I haven't touched for a while.

**Comment by jojo05** [comment]
Hi Brian,

I got everything running now. Your project is impressive. I close now this issue and will open separate ones on other topics.

Just forgot to say that in Linux the main dependency is yum install glfw-devel, which should pull most dependencies but I included the list suggested by glfw go lib (but did not include glfw-devel). I assumed gcc is an obvious dependency
